### ISSUE TITLE
Desktop app using Electron

### ISSUE THREAD

**Issue by fazo96** [fazo96/ipfs-boards#78]
A desktop app makes sense:
- could bundle go-ipfs until js-ipfs is ready
- could more easily work offline
- _maybe_ could have less security concerns compared to running stuff in the browser

The web app is built using webpack's code splitting features to be as lightweight as possible, I'm not sure it's worth the hassle to support running it in Electron.

But maybe people care, so this is open for discussion

**Comment by jbenet** [comment]
:+1: for desktop app.

we could look into making a simple electron extension that bundles go-ipfs
and allows "installing apps" like ipfs-boards.

sort of like "a browser", though i'd love to make _browser extensions_
instead of _browsers_ :]

i believe can make an extension using the `web+ipfs://` or `web+fs://`
protocol handler, but i havent worked out whether we can bundle go-ipfs
sanely. likely we will need installers with an os-level app (station?) AND
browser extensions.

(btw electron is waaaay too heavy :( it saddens that running an ipfs
indicator has to be so heavy. any hopes of electron becoming smaller?)

cc @Dignifiedquire @diasdavid

**Comment by Dignifiedquire** [comment]
No hopes on getting it smaller, 60mb or so is the minimum for shipping node + chromium

**Comment by fazo96** [comment]
What about an electron app which is a browser but only for IPFS. It would bundle go-ipfs so that apps have access to the API, and provide an interface to bookmark sites and apps.

Maybe we should build this into Station? Or at least an app launcher? Then we can tell this app's users to install Station and add the app there to use it offline.

**Comment by Dignifiedquire** [comment]
I think bundling an "ipfs browser" with station makes a lot of sense, and taking the approach you described. Most of this is already there (bundled go version) we just need to add some magic for handling urls and an easy way to open ifps urls. 

This way you install the big package once but can use different ipfs apps from there easily

**Comment by fazo96** [comment]
:+1: @Dignifiedquire 

I think the most important part is having a way to add an App using IPFS or IPNS url then opening it from station and having it Just Work with the go-ipfs API.

I opened an issue on the station repo :+1:
